name: "Development Deployment Pipeline"

on: 

  workflow_run:
      workflows: ["Sonar Cloud Scan"]  #depends on sonar.yml workflow
      types:
        - completed  
  push: 
    branches: 
      - dev
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/**'
      - 'README.md'
      - '*.md'

env:
  DEPLOY_ENV: development
  DEPLOY_BRANCH: dev
  DEPLOY_PATH: ~/deployments/vibe-coding-node

jobs:
  build_and_test:
    name: Build and Test (development)
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Cache npm Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci


      - name: Running ESLint to find Code issues
        run: npx eslint . --ext .js,.ts

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy to development
    needs: build_and_test
    runs-on: self-hosted
    steps:
      - name: Configure SSH Access
        env:
          PRIVATE_KEY: ${{ secrets.HOST_TKVM064 }}
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      - name: Deploy and Restart Application
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            set -e
            cd ${{ env.DEPLOY_PATH }}
            git fetch origin ${{ env.DEPLOY_BRANCH }}
            git checkout ${{ env.DEPLOY_BRANCH }}
            git pull origin ${{ env.DEPLOY_BRANCH }}
            npm ci --production
            pm2 restart all
          EOF
