name: "My first github Actions"
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest   # or self-hosted if you're using that
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        env:
          PRIVATE_KEY: ${{ secrets.HOST_TKVM064 }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} "echo '🚀 Deploying to server...'"
