name: "My first github Actions"
on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.HOST_TKVM064 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan 172.26.100.174 >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Deploy to server
        run: |
          rsync -avz ./dist/ user@172.26.100.174:/var/www/project/

